# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 004dff00c224271eb821aa5c9d61f409c7e51e53367f8d12c2b28cc392e0aba18587c3b70b49bc478577e9a423f671041fafa2afb3e39dd79602ba4b95303914

test:
  secret_key_base: ae96ab9c3404fdeb402148aae7bcccc49bdea0b36818780f3a5231c0a8f56f721cce073ed2c23cf53bbc2e1e63e5611ed8c6dd81af81afb206e1382f1f072a1c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
